const myData = {
  githubUsername: "isabelramirezdev",
  name: "Isabel Ramirez",
  designation: "Full stack Developer",
  avatarUrl: "/avatar.jpeg",
  email: "info@isaramdev.com",
  navmenu: [
    {
      name: "Projects",
      url: "/Projects",
      icon: "/navbar/projects.ico",
    },
    {
      name: "Skills",
      url: "/Skills",
      icon: "/navbar/skills.ico",
    },
    {
      name: "Experience",
      url: "/Experience",
      icon: "/navbar/experencies.ico",
    },
    {
      name: "About",
      url: "/About",
      icon: "/navbar/about (2).ico",
    },
    {
      name: "Contact",
      url: "/Contact",
      icon: "/navbar/contact.png",
    },
    {
      name: "Resume",
      url: "/Resume",
      icon: "/navbar/resume.ico",
    },
  ],
  projects: [
    {
      title: "Lumos AI Chat",
      link: "https://ai-chat-gkd7otv21-maria-isabel-ramirezs-projects.vercel.app/chat",
      github: "https://github.com/IsaRamDev/ai-chat",
      imgUrl: "/portafolioIsa14.png",
      description: "Multi-model AI chat interface supporting Llama, DeepSeek, Qwen, Gemma, Mistral, and Compound Beta. Built with a clean dark UI, conversation history, and real-time streaming — all in one unified chat experience.",
      stack: ["TypeScript", "React", "Next.js", "Tailwind", "AI SDK"],
      featured: true,
    },{
      title: "Harbour UI",
      link: "https://design-system-murex-kappa.vercel.app/",
      github: "https://github.com/IsaRamDev/design-system",
      imgUrl: "/portafolioIsa13.png",
      description: "Custom component design system with interactive documentation. Includes Button, Input, Badge, Card, Modal, Toggle, and Avatar components — each with live previews, status variants, and copy-ready JSX snippets.",
      stack: ["TypeScript", "React", "Next.js", "Tailwind", "Storybook"],
      featured: true,
    },{
      title: "HAVEN Storefront",
      link: "https://shop-storefront-seven.vercel.app/",
      github: "https://github.com/IsaRamDev/shop-storefront",
      imgUrl: "/portafolioIsa12.png",
      description: "Fully functional e-commerce storefront with product filtering, keyword search, 5 sort options, a dynamic cart with free-shipping progress, and smooth loading skeletons — zero heavy dependencies.",
      stack: ["Tailwind", "HTML/CSS", "Javascript", "React", "Vite.js"],
      featured: true,
    },{
      title: "Market Dashboard",
      link: "https://market-dashboard-sage-seven.vercel.app/",
      github: "https://github.com/IsaRamDev/market-dashboard",
      imgUrl: "/portafolioIsa11.png",
      description: "Real-time crypto market tracker with live prices, 7-day interactive charts, and a searchable coin table. Auto-refreshes every 60 seconds via CoinGecko API — zero auth required.",
      stack: ["Tailwind", "HTML/CSS", "Javascript", "React", "Vite.js", "Recharts"],
      featured: true,
    },{
      title: "Kaix Landing Page",
      link: "https://kaix-landing-page.vercel.app/sacvsa",
      github: "https://github.com/IsaRamDev/KAIX-LandingPage",
      imgUrl: "/portafolioIsa10.png",
      description: "High-converting marketing landing page for KAIX, built with smooth scroll animations, bold visual hierarchy, and a fully responsive layout optimized for lead generation.",
      stack: ["Tailwind", "HTML/CSS", "Javascript", "React", "Vite.js"],
      featured: true,
    },{
      title: "Luzete Fashion",
      link: "https://www.luzetefashion.com/",
      github: "https://github.com/IsaRamDev/luzete-fashion",
      imgUrl: "/portafolioIsa09.png",
      description: "Full fashion e-commerce site for Luzete, featuring a product catalog, elegant UI, and seamless mobile experience — live and serving real customers.",
      stack: ["Tailwind", "HTML/CSS", "Javascript", "React", "Vite.js"],
      featured: true,
    },{
      title: "Digital Circuit Simulator",
      link: "https://digital-circuit-simulator-pi.vercel.app/",
      github: "https://github.com/IsaRamDev/IsaRamDev-Digital-Circuit-Simulator",
      imgUrl: "/portafolioIsa08.png",
      description: "Browser-based tool to design and simulate digital logic circuits in real time. Drag-and-drop gates, connect wires, and watch outputs update instantly — no installation needed.",
      stack: ["Tailwind", "HTML/CSS", "Javascript", "React", "Vite.js"],
      featured: false,
    },{
      title: "Dev Portfolio",
      link: "https://landing-page-lac-five.vercel.app/",
      github: "https://github.com/IsaRamDev/LandingPage",
      imgUrl: "/portafolioIsa07.png",
      description: "Personal developer portfolio showcasing projects, skills, and experience. Built with Next.js and deployed on Vercel — the very site you're reading right now.",
      stack: ["Tailwind", "HTML/CSS", "Javascript", "React", "Vite.js", "Vercel"],
      featured: false,
    },{
      title: "Robocoons",
      link: "https://robocoons-lilac.vercel.app/",
      github: "https://github.com/IsaRamDev/Robocoons",
      imgUrl: "/portafolioIsa06.png",
      description: "Landing page for a teenage robotics team representing Mexico in international competitions. Built to inspire, recruit sponsors, and put young engineers on the map.",
      stack: ["Tailwind", "HTML/CSS", "Javascript", "React", "Vite.js"],
      featured: false,
    },{
      title: "Memory Game",
      link: "https://isaramdev-memory-game.vercel.app/",
      github: "https://github.com/IsaRamDev/isaramdev-memory-game",
      imgUrl: "/portafolioIsa05.png",
      description: "Interactive card-matching memory game with animated flips, win detection, and move counter. A clean example of state management and CSS transitions in React.",
      stack: ["Tailwind", "HTML/CSS", "Javascript", "React", "Vite.js"],
      featured: false,
    },{
      title: "Movies Review",
      link: "https://isaramdev-movies-review.vercel.app/",
      github: "https://github.com/IsaRamDev/isaramdev-movies-review",
      imgUrl: "/portafolioIsa04.png",
      description: "Movie discovery app powered by a public API. Browse, search, and explore films with rich metadata, posters, and ratings — all rendered in a slick responsive UI.",
      stack: ["Tailwind", "HTML/CSS", "Javascript", "React", "Vite.js"],
      featured: false,
    },{
      title: "Weather App",
      link: "https://isaramdev-weather-search.vercel.app/",
      github: "https://github.com/IsaRamDev/WeatherSearch",
      imgUrl: "/portafolioIsa03.png",
      description: "Real-time weather search app showing current conditions, temperature, and forecasts for any city worldwide. Clean design with live API data and dynamic weather icons.",
      stack: ["Tailwind", "HTML/CSS", "Javascript", "React", "Vite.js"],
      featured: false,
    },{
      title: "La Catrina MX",
      link: "https://la-catrina-mx.vercel.app/",
      github: "https://github.com/IsaRamDev/LaCatrinaMX",
      imgUrl: "/portafolioIsa02.png",
      description: "Cultural Mexican website celebrating Día de Muertos with rich visuals, vibrant colors, and immersive storytelling — a tribute to tradition built with modern web tech.",
      stack: ["Tailwind", "HTML/CSS", "Javascript", "React", "Next.js"],
      featured: false,
    },{
      title: "Daily To-Do List",
      link: "https://to-do-list-react-isaramdev.vercel.app/",
      github: "https://github.com/IsaRamDev/ToDoListReact",
      imgUrl: "/portafolioIsa01.jpg",
      description: "Clean and minimal task manager with add, complete, and delete functionality. One of the first React projects — proof that clean UI and solid state logic go hand in hand.",
      stack: ["Tailwind", "HTML/CSS", "Javascript", "React", "Next.js"],
      featured: false,
    },
  ],
  skills: {
    description:
      "This is my current tech stack, in which I feel most comfortable and where I'm trying to specialize right now.",
    languages: [
      "JavaScript", "TypeScript", "HTML/CSS", "Python", "PHP", "C++",
    ],
    frameworks: [
      "React.js", "Next.js", "React Server Components", "Angular",
      "React Native", "Vite.js", "Express.js", "Storybook", "Makeswift",
    ],
    styling: [
      "Tailwind CSS", "SASS", "Bootstrap",
    ],
    tools: [
      "Node.js", "MongoDB", "MySQL", "SQL Server", "AWS",
      "Docker", "Git/GitHub", "Figma", "Vercel", "Turborepo",
      "BigCommerce", "Shopify", "Postman", "Twilio", "Webflow",
    ],
  },
  about: {
    title:
      "I am a middle-level front-end developer with 2 years of experience in creating responsive web designs and mobile apps that are user-friendly for startups. Currently, I am working on ",
    titleEs:
      "Soy un middle-level front-end developer con 2 años de experiencia en la creación de diseños web receptivos y aplicaciones móviles fáciles de usar para startups. Actualmente, estoy trabajando en ",
    description: [
      ` I am a frontend developer with experience developing websites and applications. I have strong knowledge in technologies like React, TailwindCSS, Next JS, TypeScript and GraphQL. My focus in development is to create quality, efficient and scalable solutions to meet the needs of users. I am a frontend developer with experience developing websites and applications. I have strong knowledge in technologies like React, TailwindCSS, Next JS, TypeScript and GraphQL. My focus in development is to create quality, efficient and scalable solutions to meet the needs of users.`,
      `In my career, I have worked in interdisciplinary teams in different industries, including education, consulting, and foreign trade. Contributed to the creation of various web products in collaboration with product and back-end teams, and helped improve website performance by 50%.`,
      `I also have a solid understanding of UX/UI best practices and have implemented agile methodologies, such as Scrum, to optimize speed and scalability of applications. My commitment to work and detail has been shown in the development of reusable code and libraries for future projects.`,
      `In addition, I am fluent in English, which has allowed me to work with international teams and broaden my professional horizons. I am committed to continue learning and developing my skills to create impactful and efficient solutions for my clients.`,
      `If you are looking for an experienced fron-tend developer with a strong commitment to quality, don't hesitate to contact me.`,
    ],
    descriptionEs: [
      `He estado desarrollando páginas web desde que tenía 12 años. No sabía qué significaba ser desarrollador front-end en ese momento porque el término no se acuñaba en ese tiempo. `,
      `A medida que adquiría más experiencia, amplié mi conjunto de habilidades para incluir tecnologías modernas como React, Next JS, TypeScript, React-hook-form, Editor.js, Node.js, MySQL, Bootstrap y Tailwind, entre otras.`,
    ],
    currentCompany: "BigCommerce",
    currentProject: "Composable Storefront (Makeswift)",
    currentProjectUrl: "https://www.bigcommerce.com/",
    education: "Instituto Tecnológico de León, Guanajuato",
    languages: "Spanish & English (C2)",
  },
  experience: [
    {
      title: "Web Developer II",
      icon: "/companies/BigCommerce.png",
      company: "BigCommerce ",
      location: "Remote",
      startDate: "09/2025",
      endDate: "Current",
      companyLink: "https://www.bigcommerce.com/",
      desc: [
        "Products: BigCommerce · Makeswift · Feedonomics · Commerce",
        "• Developed, migrated, and refactored React components across a monorepo architecture, building new features, ",
          "moving components between sub-repositories, and modernizing legacy code to reduce technical debt and maintain consistency ",
          "across the composable storefront.",
        "• Identified and resolved UI bugs and rendering bottlenecks in enterprise-scale ecommerce storefronts, ",
          "applying performance optimization techniques to improve stability, user experience, and Lighthouse scores ",
          "for high-traffic deployments.",
        "• Integrated Makeswift as a visual page builder layer, enabling non-technical teams to manage storefront content ",
          "and layout independently, reducing developer dependency on routine content updates.",
        "• Proactively researched and proposed frontend improvements, continuously raising code quality and maintainability ",
          "standards across the team."
      ],
    },
    {
      title: "Mid Front-End Web Developer",
      icon: "/companies/Technologent.png",
      company: "Technologent ",
      location: "California, USA",
      startDate: "03/2024",
      endDate: "08/2025",
      companyLink: "https://www.technologent.com/",
      desc: [
        "Project: KBrain (AI-Driven Chat Solution)",
        "•	Developed and maintained React-based components, integrating machine learning APIs to enhance interactivity.",
        "•	Improved UI/UX for a seamless experience across admin panels and customer-facing pages.",
        "•	Optimized performance by reducing API calls and implementing lazy loading techniques.",
        "•	Utilized Git for version control and contributed to clear release notes and documentation."
      ],
    },
    {
      title: "Freelance Web Developer",
      icon: "/favicon.ico",
      company: "IsaRamDev",
      location: "Moroleón, Gto., México",
      startDate: "11/2023",
      endDate: "03/2024",
      companyLink: "https://isaramdev.com/",
      desc: [
        "•	Built high-quality websites, blogs, and landing pages using Next.js, Tailwind, Vite.js, and React.",
        "•	Developed Robocon’s landing page to showcase a teenage robotics team representing Mexico internationally."
      ],
    },
    {
      title: "Junior/Mid Full-Stack Developer",
      icon: "/companies/scio.png",
      company: "Scio Consulting",
      location: "Morelia, Michoacán, México",
      startDate: "08/2023",
      endDate: "11/2023",
      companyLink: "https://sciodev.com/",
      desc: [
        "Project: Pidamos.de (Delivery App Similar to Uber Eats)",
        "•	Upgraded the front-end to modern standards, improving UI/UX and maintainability.",
        "•	Boosted PWA speed by optimizing API calls and reducing unnecessary data processing.",
        "•	Full-stack development, enhancing administrative and customer-facing features."
      ],
      skills: " React, React Native, PHP - Laravel, MySQL – WorkBench, Postman, Docker, XAMPP, MyPHPAdmin, Twilio – WhatsApp Twilio",
    },
    {
      title: "Junior Full-Stack Developer",
      icon: "/companies/scio.png",
      company: "Scio Consulting",
      location: "Morelia, Michoacán, México",
      startDate: "05/2022",
      endDate: "08/2023",
      companyLink: "https://sciodev.com/",
      desc: [
        "Project: ScrubMoney (Financial App for Doctors in the US)",
        "•	Developed a full-stack mobile and web application, integrating AWS DynamoDB.",
        "•	Designed mobile UI with Figma and implemented API connectivity.",
        "•	Built an admin panel for enhanced user management and reporting."
      ],
      skills: "React, React Native, XCode, NodeJS, TypeScript, SASS, and AWS services.",
    },
    {
      title: "Junior Application Developer",
      icon: "/companies/scio.png",
      company: "Scio Consulting",
      location: "Morelia, Michoacán, México",
      startDate: " 12/2021",
      endDate: "05/2022",
      companyLink: "https://sciodev.com/",
      desc: [
        "Project: TryNow (Try Now, Buy Later – Shopify App)",
        "•	Customized features for 40+ Shopify merchants to enhance TryNow functionality.",
        "•	Led A/B testing and Google Analytics optimization to improve user experience.",
        "•	Contributed to SDK and checkout updates, improving purchase flexibility.",
      ],
      skills: "React, Shopify, JavaScript, HTML, CSS, and Liquid.",
    },
    {
      title: "Application Developer Trainee",
      icon: "/companies/scio.png",
      company: "Scio Consulting",
      location: "Morelia, Michoacán, México",
      startDate: " 09/2021",
      endDate: "12/2021",
      companyLink: "https://sciodev.com/",
      desc: [
        "Project: Pidamos.de",
        " • Developed and programmed a maintenance page, covering both frontend and backend.",
        " • Established a new path in both codes and facilitated communication using put and get commands, migrated tables from the api to the PWAs.",
      ],
      skills: "React, Laravel, MySQL, PHP, Postman, and Putty.",
    },
    {
      title: "Desarrollador Lógica Difusa",
      icon: "/companies/Tec.png",
      company: "Instituto Tecnológico de León",
      location: "León, Guanajuato, México",
      startDate: " 08/2019",
      endDate: "08/2021",
      companyLink: "https://www.tecnm.mx/",
      desc: [
        "Project: Design and Construction of a Multi-Agent System.",
        " •  Design of the multi-agent system, industrial design (SolidWorks), electrical design (Multisim), algorithm design (Linux).",
        " •  Design of a business plan; statistics, gross and net expenses, components, etc.",
        " •  Build a safe and comfortable table for Don Leoncio.",
        " •  Control the integrated automation in the table through mechanical systems and programming in Python, using the Raspberry Pi.",
        " •  Design a control system (dispenser) for the medications to be used on the table.",
        " •  Design a monitoring system to keep accurate records of the medication consumption.",
        " •  Implement fuzzy logic in the system to have a better understanding of the interactions.",
      ],
      skills: "Python, Raspberry Pi, Multisim, SolidWork, ESP32, sensores de luz, proximidad, etc., Proteus, Matlab, C++.",
    },
  ],
  socialLinks: {
    LinkedIn: "https://www.linkedin.com/in/isaramdev/",
    Github: "https://github.com/isaramdev",
  },
};

export default myData;
